sudo: false
cache: bundler
language: ruby
addons:
  chrome: stable
bundler_args: --quiet
services:
  - mysql
  - postgresql
script:
  - bundle exec rake
rvm:
  - 2.6.2
env:
  matrix:
    - SOLIDUS_BRANCH=v2.8 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v2.8 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
